#index:
#    path: /
#    controller: App\Controller\DefaultController::index

sigpac_home:
  path: /
  defaults: { _controller: App\Controller\SeguridadController::index }
  #schemes: [https]

sigpac_login:
  path: /login
  defaults: { _controller: App\Controller\SeguridadController::login }
  #schemes: [https]

sigpac_logout:
  path: /logout
  defaults: { _controller: App\Controller\SeguridadController::logout }
  #schemes: [https]